spring:
  application:
    name: spring-security
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # New database is created when application starts and destroyed when application is stopped
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
  datasource:
    # URL connection to database (spring-security is database name)
    #url:  n application-local.properties
    # H2 sql Driver
    #driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: in application-local.properties
    #password: in application-local.properties
  h2:
    console:
      enabled: true
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
springdoc:
  swagger-ui:
    enabled: false
    path: /swagger-ui
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /api/v1/docs
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
openapi:
  oAuthFlow:
    tokenUrl: /oauth
